--- 
    - name: Download Auditbeat .deb package
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.6.1-amd64.deb
        dest: /tmp
       
    - name: Install Auditbeat .deb package
      command: dpkg -i --force-confnew /tmp/auditbeat-7.6.1-amd64.deb

    - name: Copy Auditbeat config file to VM
      copy:
        src: auditbeat-config.yml
        dest: /etc/auditbeat/auditbeat.yml

    - name: Setup Auditbeat
      command: auditbeat setup

    - name: Start Auditbeat and enable on startup
      service:
        name: auditbeat
        state: started
        enabled: yes
