---
   
    - name: Download Metricbeat .deb
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
        dest: /tmp
                   
    - name: Install Metricbeat package
      command: dpkg -i --force-confnew /tmp/metricbeat-7.6.1-amd64.deb

    - name: Copy Metricbeat config file to VM
      copy:
        src: metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure the Metricbeat docker module
      command: metricbeat modules enable docker

    - name: Setup Metricbeat
      command: metricbeat setup 

    - name: Start Metricbeat and Enable Metricbeat service on startup
      service:
        name: metricbeat
        state: started
        enabled: yes


